### PR TITLE
Adds build matrix to travis to test rDNA, DNA and the manual

### PR DESCRIPTION
**Pull request by JBGruber**
This adds the build matrix for travis suggested in  #148. The tests for DNA and the manual will fail if the produced files do not surpass a certain file size. I wrote a small bash script called `test_size.sh` to test file sizes.

### CODE REVIEW

**Comment by leifeld** [comment]
That's great! Thanks! But I wonder if we shouldn't perhaps completely rely on the makefile for all these purposes (or at least the manual and jar file compilation). The makefile already contains all the code for building these things. We just have to execute it and check if the results are there and valid.

I also think the shell script for checking the file size isn't very flexible. The jar file _will_ vary in size over time, especially with changing dependencies. The size is not a very reliable indicator of whether the file is valid. I would rather include a check of whether the relevant classes are there. This can be done on the shell without any script, for example like this:

```
jar -tvf dna-2.0-beta24.jar | grep 'Dna\.class' | sed 's/.*Dna\.class$/OK/'
jar -tvf dna-2.0-beta24.jar | grep 'ExporterR\.class' | sed 's/.*ExporterR\.class$/OK2/'
```

**Comment by JBGruber** [comment]
> But I wonder if we shouldn't perhaps completely rely on the makefile for all these purposes (or at least the manual and jar file compilation).

Sorry, I don't know what you mean. The build matrix uses `make dna` and `make manual` already. Most of the other lines are just to set up the environment correctly. For `make manual` we need to first install `rDNA` and `R` as well as `LaTeX` packages.

I prefer not to have a bash script as well but couldn't think of a good test that can be done in one line. We need something with exit 1 if the test fails. Your suggestions works well with the jar. Do you have a good idea for the manual? Or do you think the file size is fine? I think a simple file exists might not always be enough in case an empty pdf is created.

**Comment by JBGruber** [comment]
I think these would be suitable tests then:

manual:

```
- actualsize=$(wc -c < "./output/dna-manual.pdf"); if [ $actualsize -lt 1000 ]; then echo size is $actualsize; exit 1; fi
```

DNA:

```
- jar -tvf ./output/dna*.jar | grep 'Dna\.class' | sed 's/.*Dna\.class$/OK/'
- jar -tvf ./output/dna*.jar | grep 'ExporterR\.class' | sed 's/.*ExporterR\.class$/OK2/'
```

**Comment by leifeld** [comment]
OK, I see what you mean about the installation. Regarding the tests, I think the test for the number of words of the manual is fine. If the shell command needs to return 0 if the test fails, we may need to change the DNA test, though. It currently prints nothing and exits with 1 if the class is not found and prints "OK" and exits with 1 if the class is found. How about this:

    if jar -tvf ./output/dna*.jar | grep 'Dna\.class'; then exit 1; else exit 0; fi

(and something similar for the other class)

**Comment by leifeld** [comment]
Thx. What are those hash tags in the makefile for?

**Comment by JBGruber** [comment]
To test if the tests really fail if the classes do not exist. I'll test the successful version next :smiley:

**Comment by JBGruber** [comment]
Ok, now hopefully everything should work!

**Comment by leifeld** [comment]
How come the jar file test is failing?

**Comment by JBGruber** [comment]
`exit 1` actually means fail. I got the order wrong somehow. I'm a bit worried what is happening to the manual though. We have an `!!! Error: Ghostscript exited with error code 127!` now which I don't get since nothing changed since the last successful test.

**Comment by leifeld** [comment]
Where are we using Ghostscript? The PDF compilation is done using texi2pdf.

**Comment by JBGruber** [comment]
`PDFCrop` is apparently using it. And `knitr` is using `PDFCrop` when `knit_hooks$set(crop = hook_pdfcrop)` (which we use). I'll just try to add `ghostscript` to the apt packages which get installed. But I'm really confused why it worked before. Maybe something in travis changed?

**Comment by leifeld** [comment]
Perhaps a different version in Xenial?

**Comment by JBGruber** [comment]
It seems the manual was succesfully maed this time. One of the last lines:

```
Output written on dna-manual.pdf (126 pages, 6485183 bytes).
```
But then
```
I/O Error: Couldn't open file './output/dna-manual.pdf.': No such file or directory.
```
I'll have another look tomorrow.

**Comment by JBGruber** [comment]
I changed the more fancy test, which counts words in the manual pdf, to a simpler one, which only takes into account the size of the file.

Everything works now in my fork: https://travis-ci.org/JBGruber/dna

The new test for `dna_addCoder()` still fails though. I tested it locally with the newest  jar but get:

```
Error in .jcall(connection$dna_connection, "V", "addCoder", name, color,  : 
  method addCoder with signature (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZZZZZZZZZZZZ)V not found
```
I assume all tests should work, once this is solved.

**Comment by leifeld** [comment]
Could this error be caused because the tests don't use the current jar file? I just added the `addCoder` function to DNA in version 2.0 beta 24 today. I can see that the tests download beta 23, but I am not sure if that's just a separate test or if beta 23 is actually used for testing the `dna_addCoder` function in rDNA?

**Comment by JBGruber** [comment]
No, all builds compile the `.jar` before `rDNA` is installed/checked. 

But: I must have used the wrong jar file when I tested this locally. After I fixed that I found out that `dna_addCoder()` produces output instead of a message for some reason. So with `expect_output()` it works.

**Comment by leifeld** [comment]
Ah okay. I was wondering because the command seemed to work here locally. I don't understand why there is output instead of a message. I am using the regular `System.out.println` command in Java, which is re-routed into the R console. Just like with any other function of that kind. Anyway, I'll change to `expect_output` then...

I noticed one other thing: For the word count test, you are using `wc`. However, you are feeding the PDF file into this command. I thought `wc` required a text file. When I count words in student essays, for example, I use something like this instead: `pdftotext paper.pdf - | tr -d '.' | wc -w -`.

**Comment by leifeld** [comment]
Looks like you've already changed to `expect_output`. Thx!

**Comment by leifeld** [comment]
Quick question: The rDNA travis build throws the following note:

```
travis_fold:start:after_success
[0Ktravis_time:start:0019f140
[0K$ Rscript -e 'covr::codecov()'

files differ in number of lines:
7,9c7
< Warning message:
< In spelling::spell_check_test(vignettes = TRUE, error = FALSE, skip_on_cran = TRUE) :
<   Failed to find package source directory
```
Is that a problem?

**Comment by JBGruber** [comment]
I use `wc -c` to display the count of bytes in a file.

Before, I used `(pdftotext "./output/dna-manual.pdf." - | wc -w)` but this lead to the `Couldn't open file` issue. I don't know why. This was the commit: https://github.com/JBGruber/dna/blob/fb34ca7202c38f59a690b6155a16827db08ea18b/.travis.yml#L44

**Comment by leifeld** [comment]
Probably because of the additional dot after `pdf`?

**Comment by JBGruber** [comment]
:man_facepalming:

**Comment by JBGruber** [comment]
About the `spelling::spell_check_test` issue: I think that should be an issue of the spelling package. And apparently not an important one. Even they themselves haven't fixed it in their testing: https://api.travis-ci.org/v3/job/482660902/log.txt

If something is misspelled, `R CMD check` will produce a NOTE.

**Comment by JBGruber** [comment]
Travis sometimes gets stuck while building the manual now. The test here failed for example, while everything went fine in the [fork](https://travis-ci.org/JBGruber/dna/builds/493556485). It will terminate after 10 minutes at the line

```
(/home/travis/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty)))
```

The difference between successful and failed runs seems to be that sometimes downloading the jar from GitHub exits with:

```
cannot open URL 'https://api.github.com/repos/leifeld/dna/releases': HTTP status was '403 Forbidden'
```
This might as well be a coincidence as I'm not sure how these two things are connected. The corresponding lines in the manual are:

```
<<eval=TRUE, echo = FALSE, warning = FALSE, results = 'hide', message = FALSE>>=
library("rDNA")
dna_downloadJar()
jarfile <- dna_init(returnString = TRUE)
jarfile <- basename(jarfile)
@
```
I would guess, we don't really need the line  `dna_downloadJar()` here anymore since `dna_init()` will look in `extdata` for the jar (where the newest compiled version should be in case of travis) and would attempt `dna_downloadJar()` anyway if nothing is found.

Can you think of a reason to keep `dna_downloadJar()` here?

**Comment by leifeld** [comment]
If the compilation of the manual works without the `dna_downloadJar` line, let's toss it out. It is necessary, however, to retrieve the name of the jar file via `dna_init` because it is recycled in the title information of the document to state what the current version is.

I think the reason must be that there were too many downloads within the last hour. I looked this up before, and the GitHub API blocks downloads after a certain number of downloads in the last hour. That's why I ultimately didn't included it in the `.onAttach` or `.onLoad` command of the package.

**Comment by JBGruber** [comment]
But it would still include the name of the jarfile when it is found in `extdata`, wouldn't it?

I guess I did invoke many tests, which could be the reason for the 403.

**Comment by leifeld** [comment]
Yes, I assume this would be the case. Can you try to remove the download line wherever its execution is unnecessary in the manual and see if it still compiles?

**Comment by JBGruber** [comment]
I think this is working well now. Do you want to merge?

**Comment by leifeld** [comment]
Will do! Thanks a lot!

**Pull request merged**
